# Generated by Django 5.0 on 2026-01-02 08:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('original_filename', models.CharField(max_length=500)),
                ('file', models.FileField(upload_to='documents/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('uploaded', 'Subido'), ('parsing', 'Parseando'), ('chunking', 'Dividiendo en fragmentos'), ('embedding', 'Generando embeddings'), ('indexing', 'Indexando en ChromaDB'), ('completed', 'Completado'), ('failed', 'Fallido')], default='uploaded', max_length=20)),
                ('progress_percentage', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('parsing_completed', models.BooleanField(default=False)),
                ('chunking_completed', models.BooleanField(default=False)),
                ('embedding_completed', models.BooleanField(default=False)),
                ('indexing_completed', models.BooleanField(default=False)),
                ('total_pages', models.IntegerField(default=0)),
                ('total_chunks', models.IntegerField(default=0)),
                ('total_images', models.IntegerField(default=0)),
                ('total_tables', models.IntegerField(default=0)),
                ('output_directory', models.CharField(blank=True, max_length=1000, null=True)),
                ('concatenated_markdown', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('processing_completed_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField()),
                ('content', models.TextField()),
                ('raw_markdown_file', models.CharField(blank=True, max_length=1000, null=True)),
                ('annotated_markdown_file', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='admin_panel.document')),
            ],
            options={
                'verbose_name': 'Página',
                'verbose_name_plural': 'Páginas',
                'ordering': ['page_number'],
                'unique_together': {('document', 'page_number')},
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(upload_to='extracted_images/%Y/%m/%d/')),
                ('image_path', models.CharField(max_length=1000)),
                ('caption', models.TextField(blank=True, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('position_in_document', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='admin_panel.document')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='admin_panel.page')),
            ],
            options={
                'verbose_name': 'Imagen',
                'verbose_name_plural': 'Imágenes',
                'ordering': ['position_in_document'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('success', 'Success')], default='info', max_length=10)),
                ('stage', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('details', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='admin_panel.document')),
            ],
            options={
                'verbose_name': 'Log de Procesamiento',
                'verbose_name_plural': 'Logs de Procesamiento',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_image', models.ImageField(upload_to='extracted_tables/%Y/%m/%d/')),
                ('table_path', models.CharField(max_length=1000)),
                ('caption', models.TextField(blank=True, null=True)),
                ('position_in_document', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='admin_panel.document')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='admin_panel.page')),
            ],
            options={
                'verbose_name': 'Tabla',
                'verbose_name_plural': 'Tablas',
                'ordering': ['position_in_document'],
            },
        ),
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_id', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('chunk_index', models.IntegerField()),
                ('metadata', models.JSONField(default=dict)),
                ('embedding_vector', models.JSONField(blank=True, null=True)),
                ('embedding_dimension', models.IntegerField(blank=True, null=True)),
                ('chromadb_id', models.CharField(blank=True, max_length=255, null=True)),
                ('indexed_in_chromadb', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='admin_panel.document')),
            ],
            options={
                'verbose_name': 'Fragmento',
                'verbose_name_plural': 'Fragmentos',
                'ordering': ['chunk_index'],
                'unique_together': {('document', 'chunk_id')},
            },
        ),
    ]
